const contactUsEmailTemplate = (name, email, subject, message) => {
  return `
    <!DOCTYPE html>
<html>
  <head>
    <title>Contact us - HustleHut</title>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <style>
      body {
        font-family: Arial, sans-serif;
        margin: 0;
        padding: 0;
        background-color: #f4f4f4;
      }
      .container {
        max-width: 600px;
        margin: 20px auto;
        padding: 20px;
        background-color: #fff;
        border-radius: 5px;
        box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
      }
      h2 {
        color: #333;
        margin-bottom: 20px;
      }
      p {
        margin-bottom: 10px;
        color: #333;
        font-size: 16px;
      }
    </style>
  </head>
  <body>
    <div class="container">
      <h2>New Contact Request</h2>
      <p>You have received a new contact request from your website.</p>
      <p>Here are the details:</p>
      <p><strong>Name:</strong> ${name}</p>
      <p><strong>Email:</strong> ${email}</p>
      <p><strong>Subject:</strong> ${subject}</p>
      <p><strong>Message:</strong> ${message}</p>

      <p>Email generated by HustleHut system.</p>
    </div>
  </body>
</html>
`;
};

module.exports = { contactUsEmailTemplate };
